title: Formula 1 app
description: Create a Formula 1 app
template:
  repo: formula-1-app-template
  name: formula-1-test-app
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Create F1 driver
    description: The first step in your course
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: 00-respond.md
      - type: createIssue
        title: Create the driver class
        body: 01-create-driver.md
  - title: Add favourite track
    description: The second step in your course
    event: issues.closed
    actions:
      - type: respond
        with: 01-respond.md
      - type: createIssue
        title: Add favourite track
        body: 02-add-favorite-track.md
    link: '{{ repoUrl }}/issues/2'
  - title: Create tracks
    description: The third step in your course
    event: issues.closed
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: 02-respond.md
      - type: createIssue
        title: Create tracks
        body: 03-create-track.md
  - title: Create races
    link: '{{ repoUrl }}/issues/4'
    description: The fourth step in your course
    event: issues.closed
    actions:
      - type: createIssue
        title: Create races
        body: 04-races.md
  - title: Calculate race performances
    description: The fifth step in your course
    event: issues.closed
    link: '{{ repoUrl }}/issues/5'
    actions:
      - type: createIssue
        title: Calculate race performances
        body: 05-calc-driver-perf.md
  - title: Display results
    description: The last step in your course
    event: issues.closed
    link: '{{ repoUrl }}/issues/6'
    actions:
      - type: createIssue
        title: Display results
        body: 06-results.md
  - title: 'Congrats, you''re done'
    description: The last step in your course
    event: issues.closed
    actions:
      - type: respond
        with: 07-finish.md
